theme: minima
title: Curso 2 de GitHub
author: Manuel Monroy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
GitHub es una forja para alojar proyectos utilizando el sistema de control de versiones Git. 
Se utiliza principalmente para la creación de código fuente de programas de ordenador. 
El software que opera GitHub fue escrito en Ruby on Rails. Desde enero de 2010, GitHub opera bajo el nombre de GitHub, Inc.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
